### ISSUE TITLE
Refine calculation of ballistic winds

### ISSUE THREAD

**Issue by Mirrafoil** [danleedham/ballistic-wind#19]
For Standoff, the ballistic wind should be calculated from the altitude slice between 1000' below drop altitude to 1000' above drop zone elevation.

For Freefall, Hi Bal should be calculated from drop altitude to 1000' below actuation altitude. Low Bal should be calculated from 1000' below actuation altitude to 1000' above DZ elevation.

**Comment by danleedham** [comment]
See changes made in: https://github.com/danleedham/ballistic-wind/commit/7e1078422bd7b32c5a50523e82823107b545380b

**Comment by danleedham** [comment]
![Altitude Definitions](https://user-images.githubusercontent.com/12582998/66064780-fb190f00-e53d-11e9-847d-057be9ffa71c.png)

**Comment by danleedham** [comment]
Quick overview of changes made to branch https://github.com/danleedham/ballistic-wind/compare/Refine-calculation-of-ballistic-winds

- Tab 2 Both types of jump offer each 1000' interval between First 1000' Above DZ to First 1000' Below Drop as inputs on Tab 2 for direction and speed. There is now no differentiation between Standoff/Freefall
- Tab 3 only computes the values requested for Standoff/Freefall for the chosen JumpType
- Tab 3 Remove bt80 lookup Array as we no longer use it
- Tab 3 Standoff Calculations just power through each altitude and calculate total values which then computes overall characteristics
- Tab 3 Finds the first HiBal altitude, and iterates over the altitudes, splitting LoBal and HiBal altitudes and creating two totals. The two totals then generate the overall characteristics for each part of the jump.

**Comment by danleedham** [comment]
My suggestion is that a few values are tested to ensure they align, as now computation is subtly different to the Spreadsheet.

**Comment by Mirrafoil** [comment]
All looks good mate. I'd drawn up pretty much exactly the same diagram in case I hadn't comminicated it well enough, but seems you've understood perfectly!

On the matter of the slight differences in calculation, let's just keep that branch available for use in the future... just in case!

**Comment by danleedham** [comment]
https://github.com/danleedham/ballistic-wind/commit/ed9df5885a49c7d6c82ff54c46b07b81821f50ff
